### ISSUE TITLE
HELP for config file

### ISSUE THREAD

**Issue by StormyWarrior8** [gildesmarais/html2rss#89]
I have created a feeds.yml file that looks like this:

`headers:
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
feeds:
channel:
  url: https://www.horoscope.com/us/horoscopes/general/horoscope-general-daily-today.aspx?sign=10
    language: en
selectors:
  items:
    selector: "div.main-horoscope"
  description:
    selector: "p"
  link:
    selector: "#src-horo-today"
    extractor: "href"
  `
And I have added that file in the lib folder.

But I also see that I should create a config file that looks like this:

`require 'html2rss'

rss =
  Html2rss.feed(
    channel: { url: 'https://stackoverflow.com/questions' },
    selectors: {
      items: { selector: '#hot-network-questions > ul > li' },
      title: { selector: 'a' },
      link: { selector: 'a', extractor: 'href' }
    }
  )

puts rss`

Where should I add this file?

So far, my app doesn't work, so I guess I'm doing something wrong... I'm a beginner, so...

**Comment by gildesmarais** [comment]
Hi!

I'm afraid the README might be a bit unclear and the interfaces to html2rss a bit unintuitive. I hope to find the time to revise it soon.

You already created a yaml file, so let's go with that.
https://github.com/gildesmarais/html2rss#usage-with-a-yaml-config-file

Since the yaml file can contain multiple feed configuration, you need to give yours a name, e.g. `horoscope` by adding it to line 4 and indent the lines below it.
Then the channel's language indention was off in line 7. I've fixed the yaml for you:

```yml
headers:
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
feeds:
  horoscope:
    channel:
      url: https://www.horoscope.com/us/horoscopes/general/horoscope-general-daily-today.aspx?sign=10
      language: en
    selectors:
      items:
        selector: "div.main-horoscope"
      title:
        selector: "strong"
      description:
        selector: "p"
      link:
        selector: "#src-horo-today"
        extractor: "href"
```

I assume you installed the gem with `gem install html2rss` already.

If you want to print the generated RSS to your command line, inside the folder with your yaml file, type:

```
ruby -e "require 'html2rss'; puts  Html2rss.feed_from_yaml_config('feeds.yml', 'horoscope')"
```

It loads the feeds.yml and selects the `horoscope` config.btw,  I already stared to work on making a nicer command line interface for such scenarios in #88.

Is printing to the command line sufficient or would you like to have the RSS available via http?
